-- CREATION OF DATABASE 
CREATE DATABASE chetan;

-- CREATION OF TABLE 
CREATE TABLE users(
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL,
gender ENUM('Male','Female','Others'),
date_of_birth DATE,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- CHECK TABLE CONTENT
SELECT * FROM users;

-- DELETE ALL THINGS FROM DATABASE
DROP DATABASE chetan;
